name: Build
on: push
jobs:
  test:
    runs-on: buildjet-4vcpu-ubuntu-2204-arm
    name: Test
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
        with:
          target: stable
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          title: "Development Build"
          files: neovim/build/bin