name: Build
on:
  schedule:
    - cron: '5 5 * * *'
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for release'
        required: false
        default: nightly
jobs:
  build:
    runs-on: buildjet-4vcpu-ubuntu-2204-arm
    name: Test
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
        with:
          target: stable
      - uses: actions/upload-artifact@v3
        with:
          name: neovim
          path: neovim/build/bin

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    env:
      GH_REPO: ${{ github.repository }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      # Must perform checkout first, since it deletes the target directory
      # before running, and would therefore delete the downloaded artifacts
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - if: github.event_name == 'workflow_dispatch'
        run: echo "TAG_NAME=${{ github.event.inputs.tag_name }}" >> $GITHUB_ENV
      - if: github.event_name == 'schedule'
        run: echo 'TAG_NAME=nightly' >> $GITHUB_ENV

      - if: env.TAG_NAME == 'nightly'
        run: |
          (echo 'SUBJECT=Nvim development (prerelease) build';
           echo 'PRERELEASE=--prerelease') >> $GITHUB_ENV
          gh release delete nightly --yes || true
          git push origin :nightly || true
      - if: env.TAG_NAME != 'nightly'
        run: |
          (echo 'SUBJECT=Nvim release build';
           echo 'PRERELEASE=') >> $GITHUB_ENV
          gh release delete stable --yes || true
          git push origin :stable || true

      - name: Publish release
        env:
          NVIM_VERSION: ${{ needs.linux.outputs.version }}
          DEBUG: api
        run: |
          gh release create $TAG_NAME $PRERELEASE --title "$SUBJECT" --target $GITHUB_SHA neovim/*
          if [ "$TAG_NAME" != "nightly" ]; then
            gh release create stable $PRERELEASE --title "$SUBJECT" --target $GITHUB_SHA neovim/*
          fi